import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ['latin']});

export const metadata = {
  title: "Blog",
  description: "Generated by mediterranio",
};

export default function RootLayout({ children }) {
  let header = (
    <header>
      <Link href={'/'}>
        <h1>
          Blog of Esteban
        </h1>
      </Link>
    </header> 
  )
  
  let footer = (
    <footer>
      <h5>Esteban Planas 2025</h5>
    </footer>
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
