import { inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = inter({ subset: ["latin"]});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog",
  description: "Generated by mediterranio",
};

export default function RootLayout({ children }) {
  let header = (
    <header>
      <Link href={'/'}>
        <h1>
          Blog of Estevan
        </h1>
      </Link>
    </header> 
  )
  
  let footer = (
    <footer>
      footer
    </footer>
  )

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
